In [2]:
import pandas as pd

In [3]:
df = pd.read_json('league-of-legends/champion_info_2.json')
obj = []
for item in df["data"]:
    obj.append(item)
champs = pd.DataFrame(obj)
champs = champs[champs["id"]>0].set_index("id")

In [4]:
games = pd.read_csv('league-of-legends/games.csv')

In [5]:
t1Wins = games[games['winner'] == 1][['t1_champ1id','t1_champ2id','t1_champ3id','t1_champ4id','t1_champ5id']]
t1Wins.columns = ['champ1','champ2','champ3','champ4','champ5']

In [6]:
t2Wins = games[games['winner'] == 2][['t2_champ1id','t2_champ2id','t2_champ3id','t2_champ4id','t2_champ5id']]
t2Wins.columns = ['champ1','champ2','champ3','champ4','champ5']

In [7]:
wins = pd.concat([t1Wins,t2Wins],sort=False)
wins.head(20)

    champ1  champ2  champ3  champ4  champ5
0        8     432      96      11     112
1      119      39      76      10      35
2       18     141     267      68      38
3       57      63      29      61      36
4       19      29      40     119     134
5       40     141      24      45      67
6       74      17     412      18      57
7      150     498      16      90      79
11      22       4      33     157      53
12      79     105      86      37      22
13     143       7     421      24      51
15      23      55      18      32      16
17     114      81      40     119     245
23     122     429     412       4       9
29     412      21     150      90      35
31     497      84      19      18      90
32      24      18     157      16      33
33      67     412      57     161      14
37      35      37      29      63      84
38     240     201      61     498     254

In [8]:
ids = pd.concat([wins["champ1"],wins["champ2"],wins["champ3"],wins["champ4"],wins["champ5"]])
sort_champs = pd.DataFrame(ids,columns=["id"])
sort_champs = sort_champs.groupby(["id"])["id"].count().reset_index(name = "wins").set_index('id')
sort_champs

     wins
id
1    1647
2     751
3    1271
4    1847
5    1674
6    1147
7    1048
8    1573
9     862
10   1018
11   3033
12   1724
13    421
14   1048
15   2017
16   3247
17   2149
18   6713
19   3019
20    648
21   3256
22   2571
23   2159
24   3347
25   2849
26    714
27    762
28    772
29   4665
30    514
..    ...
141  4807
143  1175
150  1938
154  1234
157  3948
161  1626
163   943
164   906
201  1910
202  3925
203   558
222  4087
223   779
236  3915
238  3189
240   910
245  2428
254  1519
266   354
267  2430
268   555
412  6143
420   722
421   701
427   505
429  1707
432  1785
497  3433
498  3906
516  1955

[138 rows x 1 columns]

In [9]:
champs_wins = champs.join(sort_champs)
champs_wins

,key,name,tags,title,wins
id,,,,,
266,Aatrox,Aatrox,"[Fighter, Tank]",the Darkin Blade,354
103,Ahri,Ahri,"[Mage, Assassin]",the Nine-Tailed Fox,3295
84,Akali,Akali,[Assassin],the Fist of Shadow,1484
12,Alistar,Alistar,"[Tank, Support]",the Minotaur,1724
32,Amumu,Amumu,"[Tank, Mage]",the Sad Mummy,1178
34,Anivia,Anivia,"[Mage, Support]",the Cryophoenix,1207
1,Annie,Annie,[Mage],the Dark Child,1647
22,Ashe,Ashe,"[Marksman, Support]",the Frost Archer,2571
136,AurelionSol,Aurelion Sol,"[Mage, Fighter]",The Star Forger,442
268,Azir,Azir,"[Mage, Marksman]",the Emperor of the Sands,555
432,Bard,Bard,"[Support, Mage]",the Wandering Caretaker,1785
53,Blitzcrank,Blitzcrank,"[Tank, Fighter]",the Great Steam Golem,3506
63,Brand,Brand,[Mage],the Burning Vengeance,1996
201,Braum,Braum,"[Support, Tank]",the Heart of the Freljord,1910
51,Caitlyn,Caitlyn,[Marksman],the Sheriff of Piltover,3183
164,Camille,Camille,"[Fighter, Tank]",the Steel Shadow,906
69,Cassiopeia,Cassiopeia,[Mage],the Serpent's Embrace,1352
31,Chogath,Cho'Gath,"[Tank, Mage]",the Terror of the Void,2199
42,Corki,Corki,[Marksman],the Daring Bombardier,1138
122,Darius,Darius,"[Fighter, Tank]",the Hand of Noxus,2012
131,Diana,Diana,"[Fighter, Mage]",Scorn of the Moon,1586
36,DrMundo,Dr. Mundo,"[Fighter, Tank]",the Madman of Zaun,783
119,Draven,Draven,[Marksman],the Glorious Executioner,2546
245,Ekko,Ekko,"[Assassin, Fighter]",the Boy Who Shattered Time,2428
60,Elise,Elise,"[Mage, Fighter]",the Spider Queen,1283
28,Evelynn,Evelynn,"[Assassin, Mage]",the Widowmaker,772
81,Ezreal,Ezreal,"[Marksman, Mage]",the Prodigal Explorer,2479
9,Fiddlesticks,Fiddlesticks,"[Mage, Support]",the Harbinger of Doom,862
114,Fiora,Fiora,"[Fighter, Assassin]",the Grand Duelist,1531
105,Fizz,Fizz,"[Assassin, Fighter]",the Tidal Trickster,1696
...,...,...,...,...,...
91,Talon,Talon,"[Assassin, Fighter]",the Blade's Shadow,1589
44,Taric,Taric,"[Support, Fighter]",the Shield of Valoran,1361
17,Teemo,Teemo,"[Marksman, Assassin]",the Swift Scout,2149
412,Thresh,Thresh,"[Support, Fighter]",the Chain Warden,6143
18,Tristana,Tristana,"[Marksman, Assassin]",the Yordle Gunner,6713
48,Trundle,Trundle,"[Fighter, Tank]",the Troll King,933
23,Tryndamere,Tryndamere,"[Fighter, Assassin]",the Barbarian King,2159
4,TwistedFate,Twisted Fate,[Mage],the Card Master,1847
29,Twitch,Twitch,"[Marksman, Assassin]",the Plague Rat,4665
77,Udyr,Udyr,"[Fighter, Tank]",the Spirit Walker,553
6,Urgot,Urgot,"[Fighter, Marksman]",the Dreadnought,1147
110,Varus,Varus,"[Marksman, Mage]",the Arrow of Retribution,1442
67,Vayne,Vayne,"[Marksman, Assassin]",the Night Hunter,5498
45,Veigar,Veigar,[Mage],the Tiny Master of Evil,1933
161,Velkoz,Vel'Koz,[Mage],the Eye of the Void,1626
254,Vi,Vi,"[Fighter, Assassin]",the Piltover Enforcer,1519
112,Viktor,Viktor,[Mage],the Machine Herald,837
8,Vladimir,Vladimir,"[Mage, Tank]",the Crimson Reaper,1573
106,Volibear,Volibear,"[Fighter, Tank]",the Thunder's Roar,594
19,Warwick,Warwick,"[Fighter, Tank]",the Uncaged Wrath of Zaun,3019
498,Xayah,Xayah,[Marksman],the Rebel,3906
101,Xerath,Xerath,"[Mage, Assassin]",the Magus Ascendant,894
5,XinZhao,Xin Zhao,"[Fighter, Assassin]",the Seneschal of Demacia,1674
157,Yasuo,Yasuo,"[Fighter, Assassin]",the Unforgiven,3948
83,Yorick,Yorick,"[Fighter, Tank]",Shepherd of Souls,744
154,Zac,Zac,"[Tank, Fighter]",the Secret Weapon,1234
238,Zed,Zed,"[Assassin, Fighter]",the Master of Shadows,3189
115,Ziggs,Ziggs,[Mage],the Hexplosives Expert,1192
26,Zilean,Zilean,"[Support, Mage]",the Chronokeeper,714
143,Zyra,Zyra,"[Mage, Support]",Rise of the Thorns,1175

In [10]:
main_role = []
for id, items in champs_wins['tags'].items():
    main_role.append(items[0])
champs_wins["main_role"] = main_role

In [23]:
winners = {
    "ids":[],
    "names":[],
    "roles":[],
    "titles":[],
    "wins":[]
}
for role in champs_wins["main_role"].unique():
    maxi = champs_wins[champs_wins["main_role"] == role]["wins"].max()
    values = champs_wins[champs_wins["wins"] == maxi].values[0]
    winners["names"].append(values[0])
    winners["roles"].append(values[5])
    winners["titles"].append(values[3])
    winners["wins"].append(values[4])
df = pd.DataFrame()
df["names"] = winners["names"]
df["roles"] = winners["roles"]
df["titles"] = winners["titles"]
df["wins"] = winners["wins"]
df.sort_values("wins",ascending=False).reset_index(drop=True)

        names     roles                  titles  wins
0    Tristana  Marksman       the Yordle Gunner  6713
1      Thresh   Support        the Chain Warden  6143
2        Kayn   Fighter       the Shadow Reaper  4807
3         Lux      Mage  the Lady of Luminosity  3560
4  Blitzcrank      Tank   the Great Steam Golem  3506
5         Zed  Assassin   the Master of Shadows  3189